#cloud-config
variables:
  DB_NAME: taskdb
  DB_USER: root
  DB_PASSWORD: password
  API_PORT: 5000

package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - mysql-server
  - npm

runcmd:
  - systemctl start mysql
  - mysql -e "CREATE DATABASE $DB_NAME;"
  - pip3 install flask flask-sqlalchemy pymysql
  - "cd /opt/backend && nohup python3 app.py &"
  - "cd /opt/frontend && npm install && npm run build && serve -s build"
